---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-argocd
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-argocd-sa
  interval: 1m0s
  path: ./argocd
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-poc
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: argocd-server
      namespace: tanzu-system-monitoring


