---
ingress:
  enabled: true
  virtual_host_fqdn: "prometheus.system.tanzu"
  prometheus_prefix: "/"
  alertmanager_prefix: "/alertmanager/"
  prometheusServicePort: 80
  alertmanagerServicePort: 80
prometheus:
  pvc:
    ### Enter storage class
    storageClassName: vc01cl01-t0compute
alertmanager:
  pvc:
    ### Enter storage class
    storageClassName: vc01cl01-t0compute
