---
grafana:
  secret:
    type: "Opaque"
    # base64 encoded, VMware1!
    admin_password: "Vk13YXJlMSE="
  pvc:
    # Add storage class here
    storageClassName: vc01cl01-t0compute
ingress:
  enabled: true
  # Set the FQDN - make entry in DNS provider
  virtual_host_fqdn: "grafana.tkgs.tanzu-studio.com"
  prefix: "/"
  servicePort: 80

