apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: argocd-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: argocd-packages-sa
  namespace: packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: argocd-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: argocd-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: argocd-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: argocd-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: argocd-packages-sa
  namespace: packages
