---
grafana:
  secret:
    type: "Opaque"
    admin_password: "Vk13YXJlMSE="
  pvc:
    storageClassName:
ingress:
  enabled: true
  ### Add FQDN
  virtual_host_fqdn: "grafana.tkg.tanzu-studio.com"
  prefix: "/"
  servicePort: 80

