---
grafana:
  secret:
    type: "Opaque"
    admin_password: "Vk13YXJlMSE="
  pvc:
    ### Add storage class
    storageClassName: vc01cl01-t0compute
ingress:
  enabled: true
  ### Add FQDN
  virtual_host_fqdn: "grafana.tkg.tanzu-studio.com"
  prefix: "/"
  servicePort: 80

