---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: argocd-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: argocd-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: argocd-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: argocd-packages-sa
    kapp.k14s.io/update-strategy: "fallback-on-replace"
    kapp.k14s.io/create-strategy: "fallback-on-replace"
  name: argocd
  namespace: packages
spec:
  packageRef:
    refName: argocd.tanzu.vmware.com
    versionSelection:
      constraints: 7.5.17+vmware.1-tkg.1
  serviceAccountName: argocd-packages-sa
  values:
  - secretRef:
      name: argocd-packages-values
